/*******************************************************************************
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * TextResources_no.java Team 12, 19 Feb 2015
 *******************************************************************************/

package no.hist.aitel.team12.resources;

import java.util.ListResourceBundle;

/**
 * This class contains the Norwegian translation of all string resources to be used.
 * Note that version number is not updated for each addition to the list.
 * 
 * @author Hallgeir
 * @version 1.0
 */
public class TextResources_no extends ListResourceBundle {

	public TextResources_no() {
	}

	@Override
	protected Object[][] getContents() {
		return new Object[][] {
				{"login", "Logg inn"},
				{"cancel", "Avbryt"},
				{"y", "Ja"},
				{"n", "Nei"},
				{"sss", "Super Shopping Surfer"},
				{"pwd", "Passord"},
				{"usr", "Brukernavn"},
				{"loginfail", "Innloging feilet.\nUgyldig brukernavn/passord."},
				{"err", "Feil"},
				{"send", "Send"},
				{"reply", "Svar"},
				{"from", "Fra"},
				{"to", "Til"},
				{"sub", "Emne"},
				{"exe", "Kjør"},
				{"overview", "Oversikt"},
				{"msgs", "Meldinger"},
				{"usrs", "Brukere"},
				{"sql", "SQL"},
				{"rport", "Rapport"},
				{"tckts", "Hendvendelser"},
				{"finance", "Finans"},
				{"reg","Registrer"},
				{"cntrTxt"," På: "},
				{"storeTxt"," Finans rapportering for: "},
				{"fDate","Fra dato: "},
				{"tDate","Til dato: "},
				{"spdf", "Vis PDF"},
				{"svpdf", " Lagre PDF"},
				{"newuser", "Ny bruker"},
				{"edituser", "Endre bruker"},
				{"regsub", "SuperShoppingSurfer - Ny bruker registrert "},
				{"msgConfirmation", "Meldingen er sendt"},
				{"businessName", "Foretningsnavn"},
				{"email", "E-post"},
				{"openingHrs", "Åpningstider"},
				{"textDescription", "Beskrivelse"},
				{"edit", "Rediger"},
				{"save", "Lagre"},
				{"nrOfFloors", "Antall etasjer"},
				{"area", "Areal  (m²)"},
				{"firstname","Fornavn"},
				{"lastname","Etternavn"},
				{"adr","Adresse"},
				{"zip","Postnummer"},
				{"tel","Telefon"},
				{"sal","Lønn"},
				{"reverr", " Ingen fortjeneste er skrevet inn"},
				{"rev", "Fortjeneste"},
				{"revdaterr", "Kan ikke registrere fortjeneste.\nDato fra/til mangler."},
				{"pdferr", "Kan ikke vise finansrapport.\nDato fra/til er ikke valgt"},
				{"daterr", "Fra dato må være før til dato"},
				{"createuser","Lagre bruker"},
				{"generating", "Genererer ..."},
				{"newTrade", "Legg til bransje"},
				{"trades", "Bransjer"},
				{"personnel", "Personell"},
				{"name", "Navn"},
				{"title", "Tittel"},
				{"centre", "Senter"},
				{"building", "Bygg"},
				{"shop", "Butikk"},
				{"cmp","Firma"},
				{"pos","Posisjon"},
				{"invalidEmail", "Ugyldig epost-addresse, prøv igjen"},
				{"invalidTel", "Ugyldig telefonnummer, oppgi 8 siffer"},
				{"delMsg", "Slett melding"},
				{"dbErr", "Noe gikk galt i databaseforbindelsen."},
				{"sysadmin", "Systemadministrator"},
				{"cntrmanager", "Senterleder"},
				{"shopowner", "Bedriftseier"},
				{"customerservice", "Kundeservice"},
				{"personnel", "Personell"},
				{"invalidZip", "Ugyldig postnummer"},
				{"usertypeTry", "Prøver å opprette brukertype: "},
				{"whatUsertype", "Hvilken type bruker skal opprettes?"},
				{"noEmpty", "Feltet kan ikke være tomt."},
				{"usertype", "brukertype"},
				{"invalidHrs", "Ugyldig format på åpningstid\nDet kreves to tall i hvert av de 4 feltene\nog man må åpne før man stenger"},
				{"invalidInt", "Ugyldig format, oppgi heltall"},
				{"shce","Kjøpesenter"},
				{"store","Butikk"},
				{"cvsCntrNam","Skriv inn navn på senter"},
				{"cvsShpNam","Skriv inn navn på butikk"},
				{"cvsCounty","Skriv inn fylke"},
				{"cvsMunici","Skriv inn kommune"},
				{"newBuilding", "Ny bygning"},
				{"store","Butikk"},		
				{"frnamelong","- Fornavn er for langt. Maks 30 bokstaver."},
				{"lsnamelong","- Etternavn er for langt. Maks 30 bokstaver."},
				{"adrlong","- Adressen er for lang. Maks 30 bokstaver."},
				{"zipfour","- Postnummeret må ha fire siffer."},
				{"zipnr","- Postnummer kan bare ha nummer, og må være fire siffer langt."},
				{"emailinv","- Epostadressen er ikke gyldig."},
				{"tlplong","- Telefonnummeret må ha 8 siffer."},
				{"tlpnr","- Telefonnummer må ha kun nummer, og være 8 siffer langt."},
				{"salnr","- Lønn må være oppgitt i nummer."},
				{"inputerr","Det var en feil i skjemaet ditt:"},
				{"centerlong", "- Kjøpesenternavnet er for langt. Maks 30 bokstaver."},
				{"userlong", "- Brukernavnet er for langt. Maks 30 bokstaver."},
				{"floor", "Etasje"},
				{"park","Parkeringsplasser"},
				{"contactCS","Kontakt kundeservice"},
				{"tradeType","Bransje"},
				{"floorPlur","Etasje(r)"},
				{"resetPwd", "Tilbakestill Passord"},
				{"manager", "Manager"},
				{"EROTICA", "Erotikk"},
				{"CLOTHING", "Klær"},
				{"SHOES", "Sko"},
				{"TRAVELGOODS", "Reiseeffekter"},
				{"HOUSEANDHOME", "Hus og hjem"},
				{"TRAVELCOMPANY", "Reiseselskap"},
				{"BAKERY", "Bakeri"},
				{"GROCERIES", "Dagligvarer"},
				{"ELECTRONICS", "Elektronikk"},
				{"WELLBEING", "Vellvære"},
				{"SPORT", "Sport"},
				{"JEWELER", "Gullsmed"},
				{"LIQUORSTORE", "Vinmonopol"},
				{"OPTICIAN", "Optikker"},
				{"MAKEUP", "Sminke"},
				{"FLORIST", "Blomsterhandler"},
				{"PHARMACY", "Apotek"},
				{"TOYSHOP", "Leketøysbutikk"},
				{"BOOKS", "Bøker"},
				{"MUSIC", "Musikk"},
				{"GAMES", "Spill og underholdning"},
				{"PETSHOP", "Dyrebutikk"},
				{"HAIRDRESSING", "Frisør"},
				{"HVAC", "VVS"},
				{"FURNITURE", "Møbler"},
				{"TEXTILES", "Tekstil"},
				{"GIFTSHOP", "Gavebutikk"},
				{"LOCKSMITH", "Låsesmed"},
				{"POSTALSERVICES", "Posttjenester"},
				{"CINEMA", "Kino"},
				{"OFFICESUPPLIES", "Kontorrekvisita"},
				{"BUILDINGMATERIALS", "Byggevarer"},
				{"RESTAURANT", "Restaurant"},
				{"CAFE", "Kafé"},
				{"changePwd", "Endre passord"},
				{"manager", "Manager"},
				{"oldPwd", "Gammelt passord"},
				{"newPwd", "Nytt passord"},
				{"repNewPwd", "Gjenta nytt passord"},
				{"usrNotFound", "Finner ikke bruker"},
				{"usrAllreadyExists", "Brukernavn opptatt"},
				{"newPwdFail", "Sjekk at nytt passord gjentas korrekt"},
				{"pwdChanged", "Passord endret"},
				{"saving", "Lagrer ..."},
				{"TAILOR", "Skredder"},
				{"ALLTRADES", "Alle bransjer"},
				{"LINGERIE", "Undertøy"},
				{"month", "Måned"},
				{"jan", "Januar"},
				{"feb", "Februar"},
				{"mar", "Mars"},
				{"apr", "April"},
				{"may", "Mai"},
				{"jun", "Juni"},
				{"jul", "Juli"},
				{"aug", "August"},
				{"sep", "September"},
				{"oct", "Oktober"},
				{"nov", "November"},
				{"des", "Desember"},
				{"shopNameLong", "- Butikknavn for langt. Maks 30 karakterer"},
				{"buildingCreated", "Byggning opprettet"},
				{"selectBuildingErr", "Et bygg må velges."},
				{"noCentreName", "- Senteret må ha et navn"},
				{"shopFloorError", "- Etasje må oppgis som heltall"},
				{"shoptlpnr", "- Butikkens telefonnummer ugyldig, oppgi 8 heltall"},
				{"shopInvEmail", "- Butikkens epost er ugyldig"},
				{"shopInvZip", "- Butikkens postkode er ugyldig"},
				{"shopAdrLong", "- Butikkens adresse er for lang. Maks 30 karakterer"},
				{"shopNameLong", "- Butikkens navn er for langt. Maks 30 karakterer"},
				{"frnameMissing", "- Brukers fornavn må fylles ut"},
				{"lsnameMissing", "- Brukers etternavn må fylles ut"},
				{"usrNameMissing", "- Brukernavn må fylles ut"},
				{"titleMissing", "- Brukers tittel må fylles ut"},
				{"titleLong", "- Brukers tittel er for lang. Maks 30 karakterer"},
				{"adrMissing", "- Adresse mangler"},
				{"usrCreated", "- Bruker opprettet"},
				{"shopNameMissing", "- Butikkens navn må fylles ut"},
				{"revReg", "Fortjeneste er registrert"},
				{"needTo", "- Du må fylle inn en mottaker"},
				{"needSub", "- Du må fylle inn et emne"},
				{"$", "mrd."}
		};
	}
}
